### ISSUE TITLE
Concern about the key import

### ISSUE THREAD

**Issue by majinghe** [james-callahan/example-gitops#1]
Hi James

I am trying to use gpg with argocd following your instructions, but i got the error, detail info is [here](https://github.com/viaduct-ai/kustomize-sops/issues/85). I just wonder about the below config
```
      initContainers:
        - name: import-gpg-key
          image: argoproj/argocd:v1.5.5
          command: ["gpg", "--import", "/deploy-pgp-key/deploy-key.asc"]
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          volumeMounts:
            - mountPath: /deploy-pgp-key
              name: deploy-pgp-key
              readOnly: true
            - mountPath: /gnupg-home
              name: gnupg-home
```
The import is about to import public key or private key.  After my configuration, i got empty private when using `gpg -K`  to list, which leads to the decryption error.

Cloud you please help to do me a favor? This blocks me for a long time. Thanks a lot.

**Comment by james-callahan** [comment]
How did you create `deploy-key.asc`? It needs to contain the gpg private key

**Comment by majinghe** [comment]
Oh, my god, i contains the public key, let try with the private keys.

**Comment by majinghe** [comment]
I tried to import the private
```
$ gpg -k
/home/argocd/.gnupg/pubring.kbx
-------------------------------
pub   rsa3072 2021-01-02 [SC] [expires: 2023-01-02]
      8F5D08B6669F3F4855B1568F2C60B7289BD33768
uid           [ unknown] majinghe <majinghe@sina.com>
sub   rsa3072 2021-01-02 [E] [expires: 2023-01-02]
```
```
$ gpg -K
/home/argocd/.gnupg/pubring.kbx
-------------------------------
sec   rsa3072 2021-01-02 [SC] [expires: 2023-01-02]
      8F5D08B6669F3F4855B1568F2C60B7289BD33768
uid           [ unknown] majinghe <majinghe@sina.com>
ssb   rsa3072 2021-01-02 [E] [expires: 2023-01-02]
```

But got the same error
```
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../../base': '/tmp/git@github.com_devops_devops/kustomize/accesshub/base' must resolve to a file"
	* accumulateDirector error: "recursed accumulation of path '/tmp/git@github.com_devops_devops/kustomize/accesshub/base': trouble converting file 'secret/secret.ibmcr.yaml' to a resource: trouble decrypting file secret/secret.ibmcr.yaml: Error getting data key: 0 successful groups required, got 0"
```

**Comment by majinghe** [comment]
Any good suggestion about this?

**Comment by james-callahan** [comment]
> $ gpg -K
> /home/argocd/.gnupg/pubring.kbx

was this on the repo-server pod?

Also that looks like *your* key. The idea is you're meant to generate a new GPG key just for ArgoCD to use.

**Comment by majinghe** [comment]
This is nothing in `repo-server` pod, 
```
argocd@argocd-server-789fb45964-9b96x:~$ gpg -K
gpg: directory '/home/argocd/.gnupg' created
gpg: keybox '/home/argocd/.gnupg/pubring.kbx' created
gpg: /home/argocd/.gnupg/trustdb.gpg: trustdb created
argocd@argocd-server-789fb45964-9b96x:~$ gpg --list-keys
```
Does that means the gpg keys as well as secret keys should be exist in the `argocd-server` as well?

**Comment by james-callahan** [comment]
> Does that means the gpg keys as well as secret keys should be exist in the `argocd-server` as well?

no. they are only needed in the repo server.
That's why the patch only adds it to the repo-server.... https://github.com/james-callahan/example-gitops/blob/962cb3f912791dc1d925aa53ef3a4897072e3c90/argocd/argo-cd-import-pgp-key.yaml#L4

**Comment by majinghe** [comment]
```
$ gpg -K
/home/argocd/.gnupg/pubring.kbx
-------------------------------
sec   rsa3072 2021-01-02 [SC] [expires: 2023-01-02]
      8F5D08B6669F3F4855B1568F2C60B7289BD33768
uid           [ unknown] majinghe <majinghe@sina.com>
ssb   rsa3072 2021-01-02 [E] [expires: 2023-01-02]

```

Above exists in `repo-server` pod.

I will try to generate a new gpg key used by argocd.

**Comment by majinghe** [comment]
@james-callahan  Hi james, after i re-create a new gpg key, and then remove the `passphrase`, everything works fine now.

Thanks very much for your guidance.

Just a little suggestion for your configuration,  if `deploy-pgp-key` can be replaced with `deploy-pgp-secret-key`, maybe more clear, i created this secret with public key, and everything goes wrong. As per suggested by you, i changed with `private` key, then the debug is smoothly.

```
        - name: import-gpg-key
          image: argoproj/argocd:v1.5.5
          command: ["gpg", "--import", "/deploy-pgp-key/deploy-key.asc"]
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          volumeMounts:
            - mountPath: /deploy-pgp-key
              name: deploy-pgp-key
```
Anyway, thanks for your help. I will close this issue.
